###TEST
# GET http://localhost:6000 HTTP/1.1

### GET ALL ITEMS
GET http://localhost:6000/api/items HTTP/1.1

### GET SINGLE ITEM
GET http://localhost:6000/api/items/4 HTTP/1.1

### ADD ITEMS
POST http://localhost:6000/api/items HTTP/1.1
Content-Type: application/json

{
  "name": "New Item",
  "quantity": 11
}

### DELETE ITEM
DELETE  http://localhost:6000/api/items/3 HTTP/1.1

### UPDATE ITEM
PUT http://localhost:6000/api/items/1 HTTP/1.1
Content-Type: application/json

{
  "name": "New Item",
  "quantity": 110
}